name: Deploy staging
on:
  push:
    branches: [ staging ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: 'Build and push image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/spring:staging-${{ github.run_number }} -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/spring:staging-latest 
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/spring:staging-${{ github.run_number }}
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/spring:staging-latest
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'staging-spring'
        images: 'geekseat.azurecr.io/spring:staging-${{ github.run_number }}'
    
    - name: Azure logout
      run: |
        az logout
